sudo: required
services:
 - docker
 
before_install:
 - docker build -t govindaraju/docker-react -f Dockerfile.dev .
 
 
script:
 - docker run govindaraju/simplewebdocker-react npm run test -- --coverage